name: SABnzbd.org

wiki_version: '2.1' # Needs to be a string, for string-comparison

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      name: SABnzbd.org
  -
    scope:
      path: "wiki"
    values:
      layout: "wiki"
      section: "Wiki"
